### ISSUE TITLE
docker image

### ISSUE THREAD

**Issue by ppa-covis** [box/mojito#110]
Hello everyone,

this is merely a suggestion to offer mojito as a docker image on docker hub to make testing/evaluation easier.

**Comment by aurambaj** [comment]
Yes, it is a good suggestion! 

I'm going to work on a docker image soon to deploy Mojito for translationcommons.org. I'll share it once finished.

Else did you get a chance to [install using brew](http://www.mojito.global/docs/guides/getting-started/)?

**Comment by ppa-covis** [comment]
Thanks!
I'm on Ubuntu/Windows, so I haven't been able to try that yet. I think I will either wait for the docker image, or try to run it on docker myself.

**Comment by ppa-covis** [comment]
Here is my (dirty) take on a Dockerfile:

`
FROM ubuntu:16.04

RUN apt-get update && apt-get install -y software-properties-common

ENV LANG en_US.UTF-8
RUN locale-gen $LANG

RUN add-apt-repository ppa:openjdk-r/ppa

RUN apt-get update && apt-get install -y openjdk-8-jdk

ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64/
RUN export JAVA_HOME
RUN apt-get install -y build-essential curl git python-setuptools ruby git
RUN git clone https://github.com/Linuxbrew/brew.git ~/.linuxbrew
RUN ~/.linuxbrew/bin/brew tap box/mojito
RUN ~/.linuxbrew/bin/brew install mojito-cli
RUN ~/.linuxbrew/bin/brew install mojito-webapp
RUN ln -s ~/.linuxbrew/Cellar/mojito-webapp/0.56/bin/mojito-webapp /usr/bin
EXPOSE 8080
CMD ["mojito-webapp"]
`

I'm sure there are better ways to do it, but it works for now.

use it with:
`
docker build -t mojito .
docker run -d -p 8080:8080 mojito
`

**Comment by aurambaj** [comment]
Thanks @ppa-covis  for sharing!  It is a good starting point, I'll look at adding Mysql. I'm going to work on that probably end of next week.
