### ISSUE TITLE
Long keys for MySQL older than 5.7

### ISSUE THREAD

**Issue by dbek** [box/mojito#120]
The table creation process fails on MySQL 5.5.52 with the following error:

> ## Migration V1__Initial_Setup.sql failed
> 
> SQL State  : 42000
> Error Code : 1071
> Message    : Specified key was too long; max key length is 767 bytes
> Location   : db/migration/V1__Initial_Setup.sql (/usr/local/bin/file:/usr/local/bin/mojito-webapp-0.57.jar!/db/migration/V1__Initial_Setup.sql)
> Line       : 32
> Statement  : alter table asset add constraint UK__ASSET__REPOSITORY_ID__PATH unique (repository_id, path)

As fas as I can see, the "asset" table column "path" is 255 characters long, which would already exceed the 767 bytes key limit, since utf8mb4 is 4 bytes per character.

A possible workaround might be turning "innodb_large_prefix" on, but still doesnt' help on my Ubuntu 14.04 and MySQL 5.5.52

**Comment by aurambaj** [comment]
@dbek , Mysql doc also mention `innodb_file_format` could you check this config as well?

> innodb_large_prefix is enabled by default in MySQL 5.7.7. This change coincides with the default value change for innodb_file_format, which is set to Barracuda by default in MySQL 5.7.7. Together, these default value changes allow larger index key prefixes to be created when using ROW_FORMAT=DYNAMIC or ROW_FORMAT=COMPRESSED. If either option is set to a non-default value, index key prefixes larger than 767 bytes are silently truncated.

**Comment by dbek** [comment]
@aurambaj , changed it also in my.cnf, so this query:
`select @@innodb_large_prefix, @@innodb_file_format;`
now returns
`1; Barracuda`
Didn't help though, still got the same error. This definitely lies within the MySQL configuration, not an app issue, since I've tried it on MySQL 5.7.9 and it works just fine (btw, these globals have the same values of 1 and Barracuda on a newer version).

**Comment by dbek** [comment]
@aurambaj , I think a possible solution might be to add ROW_FORMAT=DYNAMIC or ROW_FORMAT=COMPRESSED to table creation, this actually helps. After setting the innodb_large_prefix=1 and innodb_file_format=Barracuda, of course.

**Comment by aurambaj** [comment]
Great that makes sense based on the documentation.

**Comment by dbek** [comment]
@aurambaj , well, shouldn't it be actually added to source code? :) I can't find another way to fix this for MySQL older than 5.7.

**Comment by aurambaj** [comment]
@dbek What do you mean by `added to source code`?

**Comment by dbek** [comment]
@aurambaj The database structure is created on first app start, right? And there is no way to specify the use of ROW_FORMAT=DYNAMIC on a table except for its create statement. This should be added as a hint for entities (which might be affected by the 767 byte key limit), or a global hibernate configuration (not sure if hibernate has this fine tuning option, quick searching shows [this stackoverflow question](http://stackoverflow.com/questions/28632984/getting-jpa-to-generate-tables-with-specified-row-format), not an elegant solution though).

**Comment by dbek** [comment]
And yes - MySQL has the 'innodb_default_row_format' global variable, but - only since 5.7 :)

**Comment by aurambaj** [comment]
@dbek  hm, I was expecting `innodb_default_row_format` to be available. I need to do some more digging ( not fan of the Hibernate hack). it might be possible to restrict the part that is indexed via hibernate annotation or change the type but I think there is other tables that would be impacted.

**Comment by dbek** [comment]
@aurambaj , in fact, I've seen that there is an option to specify the indexed length of a varchar field like so: (repository_id(186), path). Might be an acceptable option as well, if supported by previous MySQL releases.

**Comment by aurambaj** [comment]
Won't fix, assuming MySQL 5.7 is a requirement. Possible workaround is to create the schema manually.
