### ISSUE TITLE
Mojito-App Doesn't work as Background Process?

### ISSUE THREAD

**Issue by usman118591** [box/mojito#129]
I had been testing mojito for a while,and i was trying to run the app as Daemon process using Tmux as well as screen. But somehow, the app shuts down after 5-6 hours. 
Is this in design? or some one has ever experienced that?

**Comment by aurambaj** [comment]
The app shouldn't shutdown. Do you see any errors in the logs?

**Comment by usman118591** [comment]
No,I dont see any error in log file. 
I had tried checking the error in log/Apache2  but didn't find the error there.

**Comment by aurambaj** [comment]
Don't you see anything in the tmux output? or in the tomcat logs? Apache2 log won't help to see anything happening to the tomcat process.

**Comment by usman118591** [comment]
[mojito.txt](https://github.com/box/mojito/files/548504/mojito.txt)
Here is the file attached where you can see the tmux out .

**Comment by aurambaj** [comment]
Ok, nothing really useful here. Can you also check `$TMPDIR/spring.log`. It should be the same content as the console output... but just to double check. Else have you check that the java process is not there anymore? Is there any JVM error logs?

**Comment by usman118591** [comment]
Here is the spring.log fil as herein attached, I am looking for JVM error logs too now.
[mojito (2).txt](https://github.com/box/mojito/files/549755/mojito.2.txt)

**Comment by aurambaj** [comment]
according to those spring log, there is a permission issue to connect to mysql. Please check the user/credential and your config to make sure it can connect.

**Comment by usman118591** [comment]
i have created a database but its still shutting down. I am reviewing the log files again. And can you tell me please, I am placing these lines, 
```
flyway.enabled=true
l10n.flyway.clean=false
spring.jpa.database=MYSQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.datasource.url=jdbc:mysql://localhost:3306/${DB_NAME}?characterEncoding=UTF-8&useUnicode=true
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driverClassName=com.mysql.jdbc.Driver
```
in the  Demo/demo.properties  is this the right path to be placed? 
Thanks.

**Comment by aurambaj** [comment]
How did you install the app? with brew or with the jar file? in both case you will find the information in  [the install document](http://www.mojito.global/docs/guides/install/) and also [more in the configuration doc](http://www.mojito.global/docs/refs/configurations/).

`Demo/demo.properties` has nothing to do with the setup. It is coming from creating a demo project.

**Comment by usman118591** [comment]
I had  reinstalled everything from scratch but now i am getting this error when i start mojito-webapp . 
Below attached is the log file for mojito-webapp. 
[mojito_log.txt](https://github.com/box/mojito/files/563773/mojito_log.txt)

**Comment by usman118591** [comment]
Or if you want,i can mail you my server credentials,so that you can have a better look whats going on.
