### ISSUE TITLE
Typo: "reposiotry" instead of "repository"

### ISSUE THREAD

**Issue by pranav-gokhale** [box/mojito#141]
In [Line 63 on mojito/cli/src/main/java/com/box/l10n/mojito/cli/command/DemoCreateCommand.java](https://github.com/box/mojito/blob/af4e90c3510bb6c78b41ca023f211e4d3e8a0556/cli/src/main/java/com/box/l10n/mojito/cli/command/DemoCreateCommand.java#L63)

**Comment by jeeyi** [comment]
Good catch! 👀 
Thank you @pranav-gokhale.  I will fix it tomorrow.
