### ISSUE TITLE
Pushing pre-existing translations?

### ISSUE THREAD

**Issue by garyhodgson** [box/mojito#153]
Hi

This is more of a question I guess, but I'll raise it as an issue.  I don't seem to be able to find a way to push existing translations.  If I have file `a.properties` and `a_de-DE.properties` which I push to a repository I would expect the existing translations in `a_de-DE.properties` to already be uploaded as part of that asset.  Is this functionality supported and I am doing something wrong, or is it expected that all translations will occur in mojito and are fed downstream?

Thanks in advance.

**Comment by aurambaj** [comment]
This is not supported yet, the only way to import translations right now is through XLIFF.

That said, it is a totally valid feature request. I actually wanted to have an import command that can process any target files and not just XLIFF to help with on-boarding of new users.

It hasn't been implemented yet because we didn't need at Box but that would be great for Opensource.

**Comment by aurambaj** [comment]
@garyhodgson it is implemented. The command is similar to `pull` if you're familiar with it. Basic usage is `mojito import -r <repository>`. The only parameter that is new is `--source-equals-target`. It allows you to choose what to do for translations that are the same as the source strings (skip them, mark them as need translation or review or accept them). This is useful if the localized files were generated to contain all strings (with source/english strings for the untranslated ones).

Let me know if you have any question or feedback.

Thanks!!

**Comment by khanhhd** [comment]
Hello, I have an issue with `push`
I am using docker to build mojito, it running in background `docker-compose up -d`
But cannot push the exists string.properties file 
```
~/.linuxbrew/bin/mojito push -r MyRepo -s /input/

Push assets to repository: MyRepo

 - Uploading: string.properties

Unexpected error, see logs for more information
```
do you know where is the logs file ?

**Comment by aurambaj** [comment]
@khanhhd I see you've posted on Gitter as well and we can keep the discussion over there but please don't post in old issues that are unrelated to your current issue, it makes things harder to track. Either create a new one or ask in the chat.
