### ISSUE TITLE
Uncaught TypeError when trying to access the workbench

### ISSUE THREAD

**Issue by fabianhinz** [box/mojito#172]
Hi
got a really strange error while trying to access the translations in the workbench.

<img width="1438" alt="workbench" src="https://cloud.githubusercontent.com/assets/22753474/26119995/9068e52a-3a6f-11e7-98ce-d5e7dd21c1c3.png">

if I'm downloading the jar's from your latest release directly from your github repository everything is working as expected, whereas when I build the fork locally I get the above error. Obviously setting my head to the 0.73 version tag before building.
Any help is highly  appreciated.

**Comment by aurambaj** [comment]
What command did you use for the build? Anyway, it is probably a transient issue with npm/node dependencies.  Try removing the directories `webapp/node_modules/`  and `webapp/node/`

**Comment by fabianhinz** [comment]
I followed your Open Source Contributors Prerequisites on two different machines, one running windows, the other mac os. Only difference is I have jdk 8 installed. As you suggested I removed the directories and did a `mvn clean install -DskipTests=true`. The Error still persists.

**Comment by aurambaj** [comment]
JDK version shouldn't be an issue, I use 8 as well. 

I just tried from a fresh clone and I got the error as well. If I swap the `node_module` and `node` directory from a working copy and the build then works...

I'll try to dig more into it soon. Sorry for the inconvenience.

**Comment by aurambaj** [comment]
In the meantime here is a file with npm dependencies that works: [npm-shrinkwrap.json.txt](https://github.com/box/mojito/files/1008435/npm-shrinkwrap.json.txt)

The `txt` extension must be removed (can't attach json files...). Then copy `npm-shrinkwrap.json` in the the `webapp` directory and run `npm install` that should install working version of the dependencies

**Comment by fabianhinz** [comment]
works with the file you provided. Thanks.
