### ISSUE TITLE
Unexpected behaviour with mapped locales and using the same source and target folder.

### ISSUE THREAD

**Issue by garyhodgson** [box/mojito#178]
Hi,

I'm not sure if the following is necessarily a bug or a quirk of this particular set of circumstances, but mojito didn't do what I expected it would so I'll jot down the details.

We are storing the source resource files in properties files without a locale, e.g. `Example.properties`, and using only language locales for the translations, e.g. `-lm "de:de-DE,en:en-GB"` resulting in `Example_en.properties`, `Example_de.properties`.  

If the source and target directories are the same folder then during the second sync with mojito the translated resource file which matches the source locale, e.g. `Example_en.properties` is picked up as a second source resource and a set of duplicate localized files are created, e.g. `Example_en_en.properties`

(I've copied in a series of commands which recreates the problem below which hopefully shows what is going on.)

There are a couple of workarounds:
* Use separate source and target folders.
* Use the `-sr` option to filter out filenames with an underscore when pushing to mojito, e.g. `-sr "^[^_]*\.properties$"` (but this is quite brittle).
* Specify a source local (-sl) parameter which won't be picked up (we're using `-sl xx`).

I guess the correct solution would be some way to tell mojito that the files with no locale are the source resource files (`-sl ''` or `-nsl` perhaps?)

I'm not necessarily pushing for a fix, but it might be worth a mention in the documentation what the actual behaviour in this situation is.

Cheers.

```

$ java -jar mojito-cli-0.73.jar push -r myrepo -s test

  Push assets to repository: myrepo

   - Uploading: Example.properties
   --> asset id: 1941

  Running, task id: 12460
  Asset content has not changed (12460) Done

  Delete assets from repository: [1937, 1938]


  Finished


$ java -jar mojito-cli-0.73.jar pull -r myrepo -s test -t test -lm "de:de-DE,en:en-GB"

  Pull localized asset from repository: myrepo

  Localizing: Example.properties
   - Processing locale: de-DE --> test\Example_de.properties
   - Processing locale: en-GB --> test\Example_en.properties

  Finished

$ java -jar mojito-cli-0.73.jar push -r myrepo -s test

  Push assets to repository: myrepo

   - Uploading: Example.properties
   --> asset id: 1941
   - Uploading: Example_en.properties
   --> asset id: 1942

  Running, task id: 12461
  Asset content has not changed (12461) Done
  Asset content has not changed (12462) Done

  Finished


$ java -jar mojito-cli-0.73.jar pull -r myrepo -s test -t test -lm "de:de-DE,en:en-GB"

  Pull localized asset from repository: myrepo

  Localizing: Example.properties
   - Processing locale: de-DE --> test\Example_de.properties
   - Processing locale: en-GB --> test\Example_en.properties
  Localizing: Example_en.properties
   - Processing locale: de-DE --> test\Example_en_de.properties
   - Processing locale: en-GB --> test\Example_en_en.properties

  Finished
```

**Comment by aurambaj** [comment]
Thanks @garyhodgson for the detailed report! 

It is indeed a bug and should be able to provide a fix shortly. Best work around for now I think is to pass a fake root locale `-sl root`
