### ISSUE TITLE
Support for reverse proxies using URL prefix

### ISSUE THREAD

**Issue by svenherzog** [box/mojito#181]
Hi,

I tried to run mojito-webapp behind a reverse proxy via subpath, so that http://example.com/mojito hits my running mojito server on port 8080 on the same machine. Setting the **server.context-path** to "/mojito" in the _application.properties_ didn't do the trick for me, because it seems that the routes for react also need to be adjusted for the changed baseurl. 
 
Is it possible to configure the application to accomplish what I'm trying to do?

**Comment by aurambaj** [comment]
Hi! Right, the React frontend and the CLI need some development to support this. Let me look at it.

**Comment by aurambaj** [comment]
@svenherzog support for context path is implemented.

On the server side you can use `server.contextPath={contextPath}` to define the context path (eg `/mojito`). And in the CLI you must use the matching setting: `l10n.resttemplate.contextPath={contextPath}`

**Comment by svenherzog** [comment]
Thanks a lot for your fast help - it's much appreciated :-)
