### ISSUE TITLE
Add option to leveraging-copy-tm to prevent overwriting existing translation

### ISSUE THREAD

**Issue by jeeyi** [box/mojito#186]
Whenever leveraging happens, we copy over translations as well as their comments and add one more comment for the leveraging operation.  This can grow the number of comments for each translation very quickly.

Current implementation leverages everything from source repo and overwrites target repo's translations.  I think there should be an option to leveraging command to skip already translated strings to prevent such overwriting.  Then only untranslated strings get translated with leveraging and there would be just one leveraging comment for each translation.

**Comment by aurambaj** [comment]
Had a quick look at the code, most likely the translation is not overridden but just the comments are duplicated. So fixing that should fix the issue.

In `AbstractLeverager#addLeveragedTranslations` the 2 calls: `tmTextUnitVariantCommentService.copyComments` and `tmTextUnitVariantCommentService.addComment` are done regardless if a translation was added or not. 

The previous call to `tmService.addTMTextUnitCurrentVariant` is supposed to check if there is an existing translation with same content, so it should create a new one only if needed. 

Right now, it is not possible to know if the translation was added or not with what's returned. We can change the function to return an object that contains something like: `{ hasCreatedTranslation: true|false, TMTextUnitCurrentVariant}` and then check before copying the comments

**Comment by jeeyi** [comment]
Released with v0.77.
