### ISSUE TITLE
Errors while building the project

### ISSUE THREAD

**Issue by dragosv** [box/mojito#232]
While trying to build locally I encountered a lot of errors that were not present before. This is also happening on travis, but somehow the errors are ignored

[ERROR]  14% building modules 36/88 modules 52 active ...in/resources/properties/en.properties## There is an issue with `node-fibers` ##
[ERROR] `/home/username/mojito/webapp/node_modules/fibers/bin/linux-x64-57/fibers.node` is missing.
[ERROR] 
[ERROR] Try running this to fix the issue: /home/username/mojito/webapp/node/node /home/username/dev/java/m

INFO] Installed in `/home/username/mojito/webapp/node_modules/fibers/bin/linux-x64-57/fibers.node`
[INFO] 
[INFO] > node-sass@3.13.1 install /home/username/mojito/webapp/node_modules/grunt-sass/node_modules/node-sass
[INFO] > node scripts/install.js
[INFO] 
[INFO] Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/linux-x64-57_binding.node
[ERROR] Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/linux-x64-57_binding.node": 
[ERROR] 
[ERROR] HTTP error 404 Not Found
[ERROR] 
[ERROR] Hint: If github.com is not accessible in your location
[ERROR]       try setting a proxy via HTTP_PROXY, e.g. 
[ERROR] 
[ERROR]       export HTTP_PROXY=http://example.com:1234
[ERROR] 
[ERROR] or configure npm proxy via
[ERROR] 
[
2 info using npm@5.4.1
3 info using node@v8.8.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle mojito-webapp@0.0.1~prebuild: mojito-webapp@0.0.1
6 info lifecycle mojito-webapp@0.0.1~build: mojito-webapp@0.0.1
7 verbose lifecycle mojito-webapp@0.0.1~build: unsafe-perm in lifecycle true
8 verbose lifecycle mojito-webapp@0.0.1~build: PATH: /home/username/mojito/webapp/node/node_modules/npm/bin/node-gyp-9 verbose lifecycle mojito-webapp@0.0.1~build: CWD: /home/username/mojito/webapp
10 silly lifecycle mojito-webapp@0.0.1~build: Args: [ '-c',
10 silly lifecycle   'webpack --config webpack.config.js --progress --env.production' ]
11 silly lifecycle mojito-webapp@0.0.1~build: Returned: code: 2  signal: null
12 info lifecycle mojito-webapp@0.0.1~build: Failed to exec build script
13 verbose stack Error: mojito-webapp@0.0.1 build: `webpack --config webpack.config.js --progress --env.production`

**Comment by aurambaj** [comment]
it may be coming from grunt-sass, can you try removing it: https://github.com/box/mojito/pull/233?

**Comment by aurambaj** [comment]
I've committed the change, it removes the error from travis. I wasn't able to reproduce the hard failure you get, but anyway that should fix it. let me know otherwise.
