### ISSUE TITLE
Failed to Start after brew install

### ISSUE THREAD

**Issue by allamiro** [box/mojito#250]
application failed to start  errors 
[failedtostart.pdf](https://github.com/box/mojito/files/1930490/failedtostart.pdf)

**Comment by allamiro** [comment]
![2018-04-20_1010](https://user-images.githubusercontent.com/279790/39035523-0735592c-4483-11e8-8260-2068319dee0d.png)

this is the version . im running now

**Comment by allamiro** [comment]
should I down grade /

**Comment by aurambaj** [comment]
unless you need java 9 for some other tools, yes you can downgrade. You can also install multiple versions of Java on Mac with cask, jenv... (see stackoverflow, etc)

**Comment by aurambaj** [comment]
Made Java 8 as dependency in brew: https://github.com/box/homebrew-mojito/commit/6c0ca94a57c640205120493b567a15bfe703b2b2 to prevent issue with java 9/10 (it will complain for Java 7 even though Mojito works with it)
