### ISSUE TITLE
User roles and repo access

### ISSUE THREAD

**Issue by dbek** [box/mojito#280]
Hi!
I was wondering if there are any plans on adding some sort of repo access control, might be very useful for localization agencies to run a single instance of Mojito and grant access to different repos to different users/groups. Right now the only way is to keep an instance per client since everybody has access to everything, which is very inconvenient.

P.S. Is this a correct place fo a feature request? :)

**Comment by aurambaj** [comment]
Hi @dbek,

The feature would be great to have indeed but it is a big effort. We already had the same [issue](https://github.com/box/mojito/issues/119) opened for more than a year. Given the current state of contributions on the project I doubt this will happen short term. 

Feel free to jump in the [Gitter](https://gitter.im/box/mojito) to ask about features.

Closing this for now.
