### ISSUE TITLE
Make Java 8 required to run Mojito

### ISSUE THREAD

**Issue by aurambaj** [box/mojito#289]
The main reason is to be able to move to Spring 2.x (doesn't support Java 7). It would also be nice to be able to use java new features. Also Spring 1.x doesn't support new Java version (9 & 10) so moving forward we want to upgrade.

@jeeyi @ehoogerbeets Last time we talked about it, the blocker was that Mojito is deployed on Java 7 at Box. Please let me know if you could upgrade? Thanks!!

**Comment by ehoogerbeets** [comment]
We are on Java 8 now, so we should be okay.

**Comment by jeeyi** [comment]
We are on Java 8 on dev but not on prod. Let me see where I can update that.

**Comment by jeeyi** [comment]
I will work on it in this sprint 🍺

**Comment by jeeyi** [comment]
Done - https://github.com/box/mojito/pull/353 😄
