### ISSUE TITLE
Malformed xml in Android strings.xml

### ISSUE THREAD

**Issue by ehoogerbeets** [box/mojito#300]
There is good news and there is bad news. The good news is that the "one" and "other" problem has gone away with Jean's latest changes and the translations are being shared again.

The bad news is that now the xml that comes out for our Android app is malformed. It has extra opening tags for plurals and some odd name attributes. Here is a sample from our values-en-rGB/strings.xml:

```
    <string description="feed item title for file with new comments event from an unknown user" name="feed_item_title_file_commented_on_unknown">Someone commented on this file</string>
    <string description="feed item title for file with new comments event" name="feed_item_title_file_commented_on_one">%1$s commented on this file</string>
    <string description="feed item title for file with new comments event" name="feed_item_title_file_commented_on_two">%1$s and %2$s commented on this file</string>
    <string description="feed item title for file with new comments event when the second user is unknown" name="feed_item_title_file_commented_on_second_unknown">%1$s and one other person commented on this file</string>
    <plurals name="feed_item_title_file_commented_on_many">
        <item description="Feed item title when there is more than 2 users activity. The second parameter is the number of users that commented the file. E.g.: Mike and 5 others commented on this file. The string is used because we stop at 9, and show 9+ when more" quantity="one">%1$s and %2$s others commented on this file</item>
    <plurals name="feed_item_title_file_commented_on_many">
        <item description="Feed item title when there is more than 2 users activity. The second parameter is the number of users that commented the file. E.g.: Mike and 5 others commented on this file. The string is used because we stop at 9, and show 9+ when more" quantity="other">%1$s and %2$s others commented on this file</item>
    </plurals>
```

Other locales have similarly malformed xml.

**Comment by aurambaj** [comment]
@ehoogerbeets I can't reproduce with the sample data I got earlier everything seems to work fine. 
Is the issue happening on an existing repository? Maybe there is something going on with the `PluralFormUpdater` since it shows name ending in "one", "two", "unknown" (would be other?) and "many twice". That looks like a single plural unit that has been split in multiple. Also 'en-GB' should just have two forms so really something going on with the plural system. 

Can you give more info to reproduce?

**Comment by jeeyi** [comment]
Fixed -  https://github.com/box/mojito/pull/303 and released -  https://github.com/box/mojito/releases/tag/v0.86
