### ISSUE TITLE
Nginx - Too Large Request URI

### ISSUE THREAD

**Issue by sentiurin** [box/mojito#348]
When i save text translation (react-client requesting to "/api/textunits/check"), Nginx says: "414 Request URI Too Large", because method of save its GET. All string just send as query param. Its bad, because i can't save large strings and strings in which characters are escaped. String size is 8211 bytes. I up my request URI limit in Nginx config to 8kb (not recommend in Nginx docs), but server (tomcat - Yours) send me result 400 with empty response. Any thoughts on that? I think, POST method with JSON body can resolve this problem.

![image](https://user-images.githubusercontent.com/23108292/46946527-ac4e3d00-d080-11e8-9b3e-d11c3887f4f5.png)

![image](https://user-images.githubusercontent.com/23108292/46946207-ac017200-d07f-11e8-97d9-af825c47d060.png)

**Comment by sentiurin** [comment]
P.S large string is User Agreement.

**Comment by aurambaj** [comment]
@sentiurin Yes, let's move the check to a POST request

**Comment by aurambaj** [comment]
@sentiurin fixed. Please give it a try.

**Comment by sentiurin** [comment]
@aurambaj Thx, your commit resolve my problem <3
