### ISSUE TITLE
Can't pull from repository

### ISSUE THREAD

**Issue by sentiurin** [box/mojito#366]
When i tried to pull from repository, "pull" process just said "Finished" and do - nothing.

My command:
java -jar mojito-cli-0.94.jar pull -r REPONAME -t TARGET_DIR -ft MAC_STRING

**Comment by aurambaj** [comment]
Can you provide more information on how you created your repository, if you see the string in mojito and the directory layout you have? If it was working before or if you just started.

**Comment by aurambaj** [comment]
@sentiurin I can't help without more information. Feel free to reopen the issue with more details
