### ISSUE TITLE
Can't pull to a different file type

### ISSUE THREAD

**Issue by BThibaut** [box/mojito#402]
I pushed a .properties file, everythings works well.

But I can't pull to a XLIFF file.

This is what I did :
```
mojito push -r MyRepo -ft PROPERTIES -sr messages.fr.properties
mojito pull -r MyRepo -ft XLIFF
```

This is the message returned :
```
Pull localized asset from repository: MyRepo

Finished
```
And there are no files in output.

**Comment by aurambaj** [comment]
@BThibaut  Yes that's by design. The `pull` command is to generate the localized files corresponding the what was pushed with the `push` command (keeping the same file type).

What are you trying to do exactly? There are other commands that generate `XLIFFs`, but it is either to create kit for translation or export the translation memory.

**Comment by BThibaut** [comment]
The purpose is to `push` a simple key/value file used by the developers and `pull` a `XLIFF` file which is readable by a web application (Symfony).

Is it a workable way to do with Mojito ?

**Comment by aurambaj** [comment]
I see, no we don't support that use case out of the box. The output type is the same as input when working with `pull/push` commands.

You could use the `tm-export` command though to have something similar. That command exports the whole repository as XLIFF files so you'd get an XLIFF that should be similar to what you want. The only problem is that the file name of the XLIFF will be different, it is basically `{reponame}-{assetnumber}_{locale}.xliff`

```
mojito demo-create -n test
cd test
mojito tm-export -r test
```

will give you something like
```
demo.properties		
test2-1_de-DE.xliff	
test2-1_en-GB.xliff	
test2-1_fr-CA.xliff	
test2-1_ja-JP.xliff	
test2-1_nl-NL.xliff	
test2-1_ru-RU.xliff	
test2-1_zh-CN.xliff
test2-1.xliff		
test2-1_en-AU.xliff	
test2-1_es-ES.xliff	
test2-1_fr-FR.xliff	
test2-1_ko-KR.xliff
test2-1_pl-PL.xliff	
test2-1_sv-SE.xliff	
test2-1_zh-TW.xliff
test2-1_da-DK.xliff	
test2-1_en-CA.xliff	
test2-1_fi-FI.xliff	
test2-1_it-IT.xliff	
test2-1_nb-NO.xliff	
test2-1_pt-BR.xliff	
test2-1_tr-TR.xliff
```

**Comment by BThibaut** [comment]
Thank your for your answer, I tried it and it replies to my issue.
