### ISSUE TITLE
Cant write in my cmd

### ISSUE THREAD

**Issue by Pazureka** [box/mojito#413]
Im starting mojito via cmd and after its run i cant write any commands into console, no letters appear.
![tyjt](https://user-images.githubusercontent.com/12884079/53810604-9d94f380-3f57-11e9-8eae-2dc81960aad7.PNG)

**Comment by aurambaj** [comment]
@Pazureka you need to use a second console, here the terminal is used by serving and is not detached

**Comment by Flithor** [comment]
Press <kbd>Ctrl</kbd>+<kbd>Z</kbd> stop and hangup it.
Input Command `bg` make it run in backgorund.
And now you can do any other work now.

Input Command `fg` can switch it to foreground.

Can also open a new terminal.
You can try [Windows Terminal](https://github.com/microsoft/terminal)
