### ISSUE TITLE
XLIFF import cannot handle newlines in source string

### ISSUE THREAD

**Issue by ndonald2** [box/mojito#419]
Hello, I am trying out mojito for my company's iOS app. I've been impressed so far, but one significant issue I have noticed is that upon pushing an XLIFF source file, mojito appears to convert newlines in source strings into spaces.

In a few places in our app we are using explicit newlines for user-facing strings so this is not ideal (e.g. a pre-formatted email body for sending a message to support). We could break these up into multiple strings but that complicates things.

Is there a way to get mojito to preserve the newlines in source strings so translators respect the whitespace we've provided?

Thanks!

**Example**:

Original XLIFF entry (newline present in `source`)

```
      <trans-unit id="Lesson.HasSound">
        <source>This content has sound.
Connect your headphones.</source>
        <note>Text informing user this screen has sounds and to connect headphones (line break intentional - two sentences separated by line break)</note>
```

Pulled translation (newline converted to space in `source`)

```
      <trans-unit id="Lesson.HasSound">
        <source>This content has sound. Connect your headphones.</source>
        <target xml:lang="zh-Hans">此内容包含声音。 请连接耳机。</target>
<note>Text informing user this screen has sounds and to connect headphones (line break intentional - two sentences separated by line break)</note>

```

Mismatch warning on Xcode import

```
--- xcodebuild: WARNING: Source/en.lproj/Localizable.strings: Incoming development string "This content has sound. Connect your headphones." does not match "This content has sound.
Connect your headphones." (Key: "Lesson.HasSound")
```

**Comment by aurambaj** [comment]
Never played much with IOS XLIFF but I remember @jeeyi adding a filter for it which may cover what you need. The option to pass to the CLI is `-ft XCODE_XLIFF` 

@jeeyi care to comment?

**Comment by ndonald2** [comment]
Great, thanks for that suggestion! I will try that. `XCODE_XLIFF` seems to be missing from the docs, btw.

**Comment by ndonald2** [comment]
👍 verified that `-ft XCODE_XLIFF` fixes _most_ of the issues. 

**Fixes**
- Pushed source strings respect the original whitespace
- Locale mapping with `mojito pull` results in correctly named files for Xcode (e.g. `zh-Hans.xliff` instead of `en_zh-Hans.xliff` when specifying mapping `zh-Hans:zh-CN`)

**Does not fix**
- Import of existing translations from `.xliff` file using `mojito import` does _not_ properly import target strings for source strings with nonstandard whitespace (leading spaces, explicit newlines)
- Documentation should be updated to include `XCODE_XLIFF` as a format option

**Comment by aurambaj** [comment]
Just to be sure, you also pass the option during the import `-ft XCODE_XLIFF`? if so can you share an example of file that doesn't import?

**Comment by ndonald2** [comment]
Yes I did pass the option:

`mojito import -r ios-demo -t localization/exported/en.xcloc/Localized\ Contents -s localization/translated -ft XCODE_XLIFF`

I'm not sure I can share the file itself as it might be considered proprietary info. But here is an example of a translation that does not import. The source string was successfully pushed but import did not result in the target string being populated in the mojito database.

```
      <trans-unit id="Coaching.Cell.DurationFormat">
        <source> %i min</source><target> %i分钟</target>
        <note>Format for indicating the duration the coaching session will take: {number_of_minutes} min</note>
      </trans-unit>
```

All of the untranslated strings showing in the mojito web app after the import have either leading spaces or explicit line breaks, so it seems to be a distinct pattern.

**Comment by jeeyi** [comment]
@ndonald2 Have you tried with `xml:space="preserve"` in order to preserve white space? For example, 
```
      <trans-unit id="Coaching.Cell.DurationFormat" xml:space="preserve">
        <source> %i min</source><target> %i分钟</target>
        <note>Format for indicating the duration the coaching session will take: {number_of_minutes} min</note>
      </trans-unit>
```
I will update the documentation for `XCODE_XLIFF`. Thank you!

**Comment by ndonald2** [comment]
@jeeyi thank you for the suggestion! I will try that. Currently this only affects a small number of strings (< 10) so adding the missing translations manually is not difficult either way.

BTW - I work at BetterUp, I think our team was on a localization strategy call with you and an engineer from Pinterest a few weeks ago? Small world :)

**Comment by jeeyi** [comment]
It was nice to meeting you all! @ndonald2 Let us know if you have more questions :)
