### ISSUE TITLE
Android Strings unwanted character escape

### ISSUE THREAD

**Issue by astulnikov** [box/mojito#437]
Whenever I pull resources with Mojito with tags inside the string, tags are being escaped.
For example "<annotation" becomes "&lt;annotation" but I need it to stay unchanged. Is there any way to disable escaping? 
Thank you for an amazing product!

**Comment by aurambaj** [comment]
@astulnikov look like the code got removed when posting the comment, I suspect it is something with &lt? Is there a closing tag?

Is "annotation" a special tag supported by android? We don't escape some tags like "i", "b", etc but I don't see any mention about "annotation"

As it is now, you can't specify extra tag, but we can look into having an option. There is already a different escaping that is available but not used by default. We could build on top of that

**Comment by astulnikov** [comment]
You are right: &lt; - it is. 
"annotation" is a special tag supported by android to make text styling easier for multi locales texts. 
I can see that <b> and some other tags are remaining. Maybe there is a way to leave out "annotation" as well?
Example of such a string resource:
    <string name="text">By signing up, I confirm I have read and agreed to <annotation link="link">User Agreement</annotation></string>
Thanks in advance!

**Comment by aurambaj** [comment]
We can add "annotation" to the list. I didn't know about that tag. For the record, documentation is here: https://developer.android.com/guide/topics/resources/string-resource#StylingWithAnnotations.

Should be a simple addition.

**Comment by astulnikov** [comment]
Exactly! I will very much appreciate. Looking forward to the new release.
And thanks again for the super quick reaction!

**Comment by astulnikov** [comment]
Hi there! Thank you guys for the super quick reaction! Now I wonder if there a next release coming any soon?

**Comment by jeeyi** [comment]
I will make it happen today! @astulnikov

**Comment by jeeyi** [comment]
@astulnikov Release v0.98 is now available!

**Comment by astulnikov** [comment]
Amazing! Thank you very much!!!
