### ISSUE TITLE
Import drop non-interactive

### ISSUE THREAD

**Issue by dragosv** [box/mojito#462]
In order to automate usage of mojito drop import I need to be able to just import the last drop if it exists, without any interaction. Something like -y or --force would be my idea.

Willing to take on this, any suggestion/guidance?

**Comment by aurambaj** [comment]
right now, the prompt is aksing for the drop id. Do you want to import all drops?

**Comment by dragosv** [comment]
All the drops that are fetched would be my goal, as the --number-drops-fetched 1 parameter allows filtering to only last one.

**Comment by aurambaj** [comment]
I'd say `-y` is usually used to automatically say "yes" to prompt question. here it is slightly different, I'd say something like `import-fetched` ? I was thinking about `import-all` that can be a little bit confusing: "all that were fetched" or "all regardless of pagination". Thoughts? 

Anyway regardless of the name, the implementation would just loop over the drops that were fetched and do the import.

**Comment by dragosv** [comment]
import-fetched sounds just right to me.

**Comment by aurambaj** [comment]
Will you be working on this one @dragosv ?

**Comment by dragosv** [comment]
Yes, I plan on working on it, except if you prefer to take over.

**Comment by aurambaj** [comment]
all yours @dragosv :)
