### ISSUE TITLE
missing langugae: Romansh language

### ISSUE THREAD

**Issue by ganti** [box/mojito#491]
the language [Romanish](https://en.wikipedia.org/wiki/Romansh_language) is missing. it may be used with the county as`rm-CH` as described in [ISO 639-1](https://www.loc.gov/standards/iso639-2/php/code_changes_bycode.php?code_ID=373)

**Proposal**: add Romanish as language to mojito: with the language code: `rm-CH`

**Comment by aurambaj** [comment]
@ganti do you need build or do you build by yourself?

**Comment by ganti** [comment]
thx for asking. we install it with brew, therefore it would be neat to have this language in the release. i can wait until the PR has been merged.

**Comment by aurambaj** [comment]
> @aurambaj thx for asking. we install it with brew, therefore it would be neat to have this language in the release. i can wait until the PR has been merged.

@jeeyi When you get a chance :) Thanks!!

**Comment by jeeyi** [comment]
@ganti v0.103 will be ready in an hour.
