### ISSUE TITLE
unit test failure

### ISSUE THREAD

**Issue by ehoogerbeets** [box/mojito#495]
In the plain unmodified master, I see this when I run all the unit tests in web app:

```
Results :

Failed tests: 
com.box.l10n.mojito.service.branch.notification.BranchNotificationServiceTest.allNotfication(com.box.l10n.mojito.service.branch.notification.BranchNotificationServiceTest)
  Run 1: BranchNotificationServiceTest.allNotfication:80->WSTestBase.waitForCondition:134 Branch2 translated notification must be sent
  Run 2: BranchNotificationServiceTest.allNotfication:80->WSTestBase.waitForCondition:134 Branch2 translated notification must be sent


Tests run: 605, Failures: 1, Errors: 0, Skipped: 28
```

Anyone know what this is?

**Comment by aurambaj** [comment]
I don't remember, flakiness with that test. Does it happen every time you run it?  

Do you have some special configurations compare to what runs on Travis? Do you use Mysql or HsqlDB?

**Comment by ehoogerbeets** [comment]
I don't think I have any special config... I just forked the repo, cloned it, then in the master branch do `mvn clean install` and I see that failure... (I think that uses hsqldb, right?)

The weird thing is, my PR for translation history has a travis build check that does not have this problem. Also, Jee tried it on her machine and doesn't see this problem either.

Maybe I have a slightly different version of Java 1.8 or something? I will check with Jee tomorrow about her exact versions of everything.

**Comment by aurambaj** [comment]
is this still an issue or can it be closed?

**Comment by ehoogerbeets** [comment]
This does not occur on my machine any more...
