### ISSUE TITLE
Full document link incorrect!

### ISSUE THREAD

**Issue by zslucky** [box/mojito#539]
the link looks like incorrect...

**Comment by aurambaj** [comment]
Hi @zslucky , are you talking about the "Ful documentation" link from github project page to the documentation: https://github.com/box/mojito#full-documentation? That's working here. What error are you getting?

**Comment by zslucky** [comment]
@aurambaj thanks for reply, I means [http://mojito.global/docs/](http://mojito.global/docs/)

**Comment by aurambaj** [comment]
that link should be working fine at least it does here. Let me know what is your issue.

**Comment by zslucky** [comment]
sorry, looks like my firewall issue.
