### ISSUE TITLE
Do not fallback to default language if the string is not translated

### ISSUE THREAD

**Issue by nzakharchenko** [box/mojito#546]
Hi there!

Right now, if some strings are not translated and I'm doing export to Android format - the strings from default language will be used. Sometimes this is not useful so it would be great to have a possibility to disable such stuff. Is there such an option?

**Comment by aurambaj** [comment]
@nzakharchenko yes, you can use  ``` --inheritance-mode
       Inheritance Mode. Used when there is no translations in the target locale
       for a text unit. (USE_PARENT to fallback to parent locale translation,
       REMOVE_UNTRANSLATED to remove the text unit from the file
       Default: USE_PARENT
       Possible Values: [REMOVE_UNTRANSLATED, USE_PARENT]```

**Comment by nzakharchenko** [comment]
@aurambaj oh, nice! Somehow I've missed that in the documentation! That's exactly what I need. Thank you!

**Comment by aurambaj** [comment]
You're welcome!
