### ISSUE TITLE
Wrong format for the empty Android string file

### ISSUE THREAD

**Issue by nzakharchenko** [box/mojito#547]
Hi there!

as a followup for https://github.com/box/mojito/issues/546, after using the flag `--inheritance-mode REMOVE_UNTRANSLATED` during pulling the string, I'm getting the following file (`string.xml`) if the strings are not translated:

```
<?xml version="1.0" encoding="utf-8"?>


</resources>
```

Problem is here that opening tag `<resource>` is missing.

Also, we need to have a copyright statement on the top of the file, is there any possibility to define a template for the pull?

Many thanks in advance!

**Comment by aurambaj** [comment]
For the copyright, you mean you have it in the original file but it gets stripped? Is it right after the prolog? Might be removed with the `<resource>` tag? Is it present when not using `--inheritance-mode REMOVE_UNTRANSLATED`?

**Comment by nzakharchenko** [comment]
@aurambaj yep, copyright exist in original language file and it gets removed when using this option.
Mmm, not sure what is prolog, but I see this file  just after executing `pull` command.
And if I don't use this flag - it works fine.

**Comment by aurambaj** [comment]
the prolog is `<?xml version="1.0" encoding="utf-8"?>`. So I guess the copyright is missing for the same reason `<resource>` is missing, it just got drop with the text unit that has no translation. I'll try to have a look tonight.

**Comment by aurambaj** [comment]
@nzakharchenko this should be fixed now. Do you need release or you build/release yourself?

**Comment by nzakharchenko** [comment]
@aurambaj thank you for so fast fix! Yeah, we need a release.

**Comment by jeeyi** [comment]
@nzakharchenko Just released v0.109. Thank you!

**Comment by nzakharchenko** [comment]
@jeeyi great! thank you for so fast replay and fix! 😻
