### ISSUE TITLE
Travis build status are not reported in Github

### ISSUE THREAD

**Issue by aurambaj** [box/mojito#591]
We used to have travis build status reported on the branch/commit that were pushed to Github. Same was true for pull-request. Now, It is not working anymore. Looks like the build is done but reporting back to github doesn't happen

@jeeyi Looks like I don't have full access to travis anymore. Could you have a look please?

<img width="1074" alt="Screen Shot 2020-06-17 at 4 32 26 PM" src="https://user-images.githubusercontent.com/9702182/84961037-23d73980-b0b8-11ea-99d4-763e2451f471.png">

**Comment by jeeyi** [comment]
It works for me.
<img width="621" alt="Screen Shot 2020-06-18 at 9 01 27 AM" src="https://user-images.githubusercontent.com/17402500/85044357-59c10000-b142-11ea-80e1-49dc6810140b.png">

Check your settings and check if Travis CI has access to your account. Settings -> Applications -> Authorized OAuth Apps:
<img width="827" alt="Screen Shot 2020-06-18 at 9 02 34 AM" src="https://user-images.githubusercontent.com/17402500/85044478-89700800-b142-11ea-87a2-5378b33305bb.png">

**Comment by aurambaj** [comment]
seems to show up for me this morning too. Thanks for "the fix" :D

I've read on google that some people had intermittent issue like this... closing for now.

**Comment by aurambaj** [comment]
@jeeyi this is happening again. One thing I don't remember exactly also is how the initial setup was done. I think we use the "pro" travis but in your screenshot there is both "Travis CI/pro" and "Travis CI for Open Source". As far as I remember one is on `travis-ci.org` and the other one is on `travis-ci.com`. When I go to `travis-ci.com` i don't see anything anymore which i guess make sense since I"m not in the Box organization anymore. I see the build in `travis-ci.org`, things are built it is just github that is not updated

**Comment by aurambaj** [comment]
Setup Github action to build and run the test. It seems to have bring back the report for travis too. Will keep both for now
