### ISSUE TITLE
Bug: Need translation values not visible after upgrade

### ISSUE THREAD

**Issue by digi-prerok** [box/mojito#594]
Hi,

First, I would like to thank you for providing this project, it has been very helpful for us to keep track of the translations to the various languages. I do have a small issue I just ran into and would appreciate any help that you can provide.

I am attempting to upgrade the mojito installation from v0.83 to v0.105 and have a problem that after the upgrade all repositories are listed as Done.

Before the upgrade "Need Translation" column in the Repositories overview listed how many translations are still needed for a repository (for example, one repository listed "139 ( 561 words )"). After the upgrade, the values are not listed and all the repositories are marked as "Done".

If I navigate to a repository and change a translation (for example, if I add a space to an existing translation or if I enter a new translation) then the value for the "Need translation" reappears for that repository (and is correct).

The problem is that I do not wish to do any updates on the translations. I am only maintaining the installation and not actually working on the translations themselves, so I would prefer to not do any modifications to the data.

Thank you in advance for your time and any assistance you can provide.

Prerok

**Comment by jeeyi** [comment]
Hello Prerok,

Thank you for using Mojito. The problem you saw may be from the changes in
how we keep track of repository stats.

Jean - is there an option to force repository stats to be re-computed?

Jee

**Comment by aurambaj** [comment]
@jeeyi we don't have a command to re-trigger statistique computation manually. 

@digi-prerok the next time you push content to the repositories it should also recompute them. I don't know if you do that on a regular basis? 

How many repositories do you have?

**Comment by ehoogerbeets** [comment]
Jean, Prerok had mentioned that he has not had new strings for a while and does not want to change the translations. Would it still cause a recomputation if he pushes the same source file as before? (ie. there will be no changes, but a push nonetheless causing a recomputation?)

**Comment by aurambaj** [comment]
re-pushing the same file won't re-trigger computation. 

Actually we have a way, through config + deployment to enable periodic computation of stats using the `l10n.repository-statistics.scheduler.cron` property

**Comment by digi-prerok** [comment]
Thanks, @aurambaj , works like a charm!

After enabling the recomputation of statistics they reappeared once the cron job activated. Thank you all, @aurambaj , @ehoogerbeets and @jeeyi for your fast response and help!

Wish you all the best in the future.
