### ISSUE TITLE
mojito-webapp: Calling depends_on :java is disabled! Use "depends_on "openjdk@11", "depends_on "openjdk@8" or "depends_on "openjdk" instead.

### ISSUE THREAD

**Issue by muzammil-convo** [box/mojito#667]
**To Reproduce**

**Run** `brew tap box/mojito fails
`
**Error:** Calling depends_on java: "1.8+" is disabled! Use depends_on "openjdk@11", depends_on "openjdk@8" or depends_on "openjdk" instead.

**Environment:**

OS: macOS Catalina
Version 10.15.7

**Comment by OlleMattsson** [comment]
I'm something similar when running operation `brew tap box/mojito`:

```
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/box/homebrew-mojito/mojito-cli.rb
mojito-cli: Unsupported special dependency :java
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/box/homebrew-mojito/mojito-webapp.rb
mojito-webapp: Unsupported special dependency :java
```

Any advice?

**Comment by aurambaj** [comment]
Fixed in https://github.com/box/homebrew-mojito/commit/90ff866bf0c6229dd563ac19f2724ef96f10c700. @OlleMattsson let me know if it working fine now.

(@muzammil-convo sorry for the late fix)

**Comment by OlleMattsson** [comment]
@aurambaj Brilliant! It's working nicely now. Cheers!

**Comment by muzammil-convo** [comment]
@aurambaj Thank you for the fix. Cheers 🍻
