### ISSUE TITLE
Mojito cannot read xliff files written by xcode 12.2

### ISSUE THREAD

**Issue by ehoogerbeets** [box/mojito#669]
Whatever parser mojito uses seems to barf on the type of xliff files that xcode 12.2 produces. The problem seems to be the `xml:space="preserve"` attribute that it now adds to the `trans-unit` tags. With that in there, pushing a new version of the xliff with the cli will exit with the following mysterious message:

```
An unexpected error happened, task=22415377
```

When you edit the xliff file by hand and take it out, the push works fine. Maybe it's an xml parser bug? Do we need to update the xml parser package?

**Comment by aurambaj** [comment]
I remember a patch is applied for xcode xliff, that's current code: https://github.com/box/mojito/blame/2b30fa80d795c3d0e3a8714c7d249e2ee22afa6f/cli/src/main/java/com/box/l10n/mojito/cli/command/CommandHelper.java#L311

Originally issue https://github.com/box/mojito/pull/128, and commit:  https://github.com/box/mojito/pull/128/commits/79c938f1b305e39d59334c4987ee9daa7f2a1561

Could it be that it is now dupplicated?

**Comment by ehoogerbeets** [comment]
Ah yes, that looks like the same thing. We are not running the latest mojito, so we don't have that fix yet... I'll close this one.
