### ISSUE TITLE
Can I import items from xlsx file?

### ISSUE THREAD

**Issue by Flithor** [box/mojito#672]
Is this feture exists?
If not, can you add the support on a specific format xlsx file?

**Comment by aurambaj** [comment]
It is not supported currently. I might be relatively easy to support since Mojito uses Okapi filters, and there is one for xlsx files: https://okapiframework.org/wiki/index.php/OpenXML_Filter. 

Do you have a sample file that could be used for testing? Not promising anything but if I can be done quickly I'd be happy to.

**Comment by Flithor** [comment]
I think it's simple to create
| | | |
|-|-|-|
|key1|string1|remark1|
|key2|string2|remark2|
|key3|string3|remark3|
|key4|string4|remark4|

just let user select the target languare when import

**Comment by aurambaj** [comment]
in your use case you'd have 1 spreadsheet/file per language? No header in the file?

(With xlsx, I'd expect people to want all the language in one sheet or eventually multiple sheet but still in a single file. That needs more investigation to know how the filter works and how it could work with the current CLI

**Comment by Flithor** [comment]
I think the simplest is the better.
no header, column 1 is key, column 2 is string, column 3 is remark.

If you want... uh... how about this:
|key|remark|en-us|fr|ko|zh-cn|
|-|-|-|
|key1|remark1|enString1|frString1|koString1|cnString1|
|key2|remark2|enString2|frString2|koString2|cnString2|
|key3|remark3|enString3|frString3|koString3|cnString3|
|key4|remark4|enString4|frString4|koString4|cnString4|

**Comment by aurambaj** [comment]
Looks like for your use case @Flithor, CSV support would work fine. Closing for now.
