### ISSUE TITLE
Can we use single repo for both Android and iOS?

### ISSUE THREAD

**Issue by mukyasa** [box/mojito#687]
Hello Mojito Team,
We were trying hands-on with product and got stuck when we were using the same repo for our Android and iOS projects it is giving error based on the repo was created and imported from the platform

Eg: if repo is created with iOS strings file and if we pull in Android project then it gives the error

`Asset with path [res/values/strings.xml] was not found in repo [Repo Name]`

**Comment by aurambaj** [comment]
Not really if you mean sharing string/translations between the two code base.

Usually Mojito is used with 1 repository by project. 

You can use 1 repository for 2 projects by adding `--push-type NO_DELETE` option .eg `mojito push -r repo --push-type NO_DELETE -s android; mojito push -r repo --push-type NO_DELETE -s ios; `. This has a side effect though: if you remove an asset from your code base, it won't be removed in Mojito.

But even if you do that, the strings won't be shared between Android and IOS, they'll be independent set of strings for each code base living in the same Mojito repository.

**Comment by mukyasa** [comment]
The main arises when we take pull, It is not syncing on both platforms, Where can I find `--push-type NO_DELETE `docs, Thanks for quick reply
