### ISSUE TITLE
[Question]: How the branches's merge works? it's not clear

### ISSUE THREAD

**Issue by emberist** [box/mojito#801]
I write in this chat, but without success 

https://gitter.im/box/mojito?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

**Comment by aurambaj** [comment]
Hi @emberist . Have you seen this [doc](https://www.mojito.global//docs/guides/branching/) ? Any specific question after reading this?

**Comment by emberist** [comment]
@aurambaj thank for the answer! I can't understand when the merge is done, can be when the string is pushed to the master branch?

**Comment by aurambaj** [comment]
The merge is done when pushing (`mojito push`) any branch. It can be a new branch, an update to an exciting branch or even deleting a branch. The new list of string is recomputed from the list of string in all the active branches. [This](https://www.mojito.global//docs/guides/branching/#primary-branch) shows the basic merge.

**Comment by emberist** [comment]
@aurambaj This is ok, but then I read this paragraph

> As a side effect, the strings won’t show up anymore in the branch they are originating from in the [dashboard](https://www.mojito.global//docs/guides/branching/#branch-dashboard). This might be confusing at first, but ideally branches should be short lived to avoid performance degradation as they will be processed each time the pushcommand is ran. They should be deleted after they are merged or after a time of inactivity.

So what happen after this hypothetical steps: 
1. I have `string1` in the `master` branch
2. I push `string2` in a new branch named `custom`
3. Then I delete the branch `custom`

Is `string2` merged? Is it in master?

**Comment by aurambaj** [comment]
The doc is outdated and the paragraph is not valid anymore. I'll remove it.

> Is string2 merged? Will be in the master branch?

Not it is not merged. `string2` will still be in the translation memory but marked as "unused". If you add `string2` to master and push, it will re-activate the "unused" string. If it was translated, the translation will come back.
