### ISSUE TITLE
using active user in Workbench/TextUnit.js

### ISSUE THREAD

**Issue by Darkalpy** [box/mojito#834]
Hello, i am trying to use active user (Users.js) in Workbench/TextUnit.js.  I am trying to do that by using createContext and createContext.Provider-Consumer. But i am always getting the same error 'Type Error: Cannot read properties of undefined (reading getSourveCreatedDate)'. Does anyone any idea to solve this issue?

**Comment by aurambaj** [comment]
@Darkalpy I don't think we currently use that pattern in the code. Also I can provide coding advice unless it is through a PR that is meant to contribute to the project.
