### ISSUE TITLE
currentUser in workbnech component

### ISSUE THREAD

**Issue by Darkalpy** [box/mojito#837]
Hi, i need to access the current user in workbench component but when i try to get it from Users.js , i am getting the error: "dispatcher not provided ". I have also tried to get it from UserClient but the error is still there. Does anyone have any idea to solve this problem?

Many greetings

**Comment by Darkalpy** [comment]
![err2](https://user-images.githubusercontent.com/64159771/183419136-90169878-2656-402a-ba16-1c47f93f61a9.png)
here you can see the error

**Comment by aurambaj** [comment]
dupplicate of #834
