### ISSUE TITLE
Fails to install on macOS Monterey 12.5

### ISSUE THREAD

**Issue by Kukiwon** [box/mojito#844]
I followed the [getting started](https://www.mojito.global/docs/guides/getting-started/) page but the installation fails on my M1 Macbook Pro with the following error:

`brew install mojito-webapp`

```
Error: openjdk@8: no bottle available!
You can try to install from source with:
  brew install --build-from-source openjdk@8
Please note building from source is unsupported. You will encounter build
failures with some formulae. If you experience any issues please create pull
requests instead of asking for help on Homebrew's GitHub, Twitter or any other
official channels.
```

When I run `brew install --build-from-source openjdk@8` I get the following error:
```
make
bootcycle-images
CONF=release

No configurations found for /private/tmp/openjdkA8-20220816-67087-1l7udti/jdk8u345-b01/! Please run configure to create a configuration.
Makefile:55: *** Cannot continue.  Stop.
```

Any thoughts on what's going on here?

**Comment by aurambaj** [comment]
looks like this `openjdk@8` dependency has not been updated to work on M1. So you'd have to install Java 8 by hand. [Adoptium / Temurin ](https://adoptium.net/temurin/releases/?version=8) has build for M1 (other provider might have them too now).

The version available on brew is getting pretty old and given it doesn't install directly my advice is to follow that [guide](https://www.mojito.global//docs/guides/install-springboot2/) instead if you have basic knowledge in git to get started
