### ISSUE TITLE
ReferenceError: Dispatcher token not provided

### ISSUE THREAD

**Issue by alperen14** [box/mojito#884]
Hi everyone, I am trying to add a new feature but when I try to upload properties with maven, I am getting the error 'Reference error: Dispatcher token not provided'. I am getting this error from SearchResultsStore.js class in onSearchParamsChanged() method in line this.waitFor(SearchParamsStore). Does anyone have any idea, how to overcome this issue?

**Comment by aurambaj** [comment]
Hi @alperen14 , can you share the code? You mention "maven" and then "javascript" classes, so I'm not sure exactly what you're trying to do

**Comment by alperen14** [comment]
Hi,
thanks for your feedback. My team was using the version 0.71 of Mojito and now we had to update it to be able to use with new features.Therefore, one of our developers deleted Gruntfile.js and karma.conf.js and updated  webpack.config.js, webpack.config_ict.js. Now we can deploy the code but getting an error "Dispatcher token not provided" because of waitFor() method. I could not find anything useful about this error in internet. Thanks again for your help!
