### ISSUE TITLE
Multiline comments (.po)

### ISSUE THREAD

**Issue by vrozkovec** [box/mojito#904]
Hello,

consider the content of .po file:

```po
#. First line
#. Second line
#. Third line
msgid "Text"
msgstr "Text translation"
```
The comment in the UI is displayed like: 
![obrazek](https://user-images.githubusercontent.com/135681/211899713-993d8356-cdf0-47c2-ad8f-add58600df98.png)

Would it be possible to display newlines? We are using comments to give more context to translators - previous and following text.

Same goes for review comment:
![obrazek](https://user-images.githubusercontent.com/135681/211901420-cf2d9587-be92-4b4c-800c-7ac523345bd8.png)

Displayed as in the text unit info
![obrazek](https://user-images.githubusercontent.com/135681/211901604-e55ff7e9-9098-4bf7-874c-f4b1a197eefb.png)

Using the most recent version of mojito, built from the master branch.

**Comment by aurambaj** [comment]
@vrozkovec should be available on master now!
