### ISSUE TITLE
Mojito Cli not working on M1

### ISSUE THREAD

**Issue by lukszar** [box/mojito#937]
I tried to install Mojito-CLI on Apple's M1 Pro chip and it results with error:

openjdk@8: The x86_64 architecture is required for this software.
Error: mojito-cli: An unsatisfied requirement failed this build.

Looks like openjdk is available just for old architecture.

**Comment by aurambaj** [comment]
right, it is not available in brew, so Java has to installed in some other way. 

Also see this comment, regarding mojito and brew: 
https://github.com/box/mojito/issues/844#issuecomment-1217192351
