### ISSUE TITLE
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by Justman10000** [box/mojito#938]

**Comment by Justman10000** [comment]
@aurambaj

**Comment by aurambaj** [comment]
closing since there is not enough information to reproduce

**Comment by Justman10000** [comment]
@aurambaj

Really? I write three fucking months ago and all you do is close issues? Instead of waiting for an answer like any normal person? If you keep this up, I won't be the only one who fucks off here
